pragma solidity ^0.8;

contract MyContract {
    // external contracts can only read the value
    // using the autogenerated getter function
    uint256 public publicUint256;
}

contract MyChildContract is MyContract {
    // derived contracts can both get and set the value

    function setValue(uint256 _value) external {
        publicUint256 = _value;
    }

    function getValue() external view returns (uint256) {
        return publicUint256;
    }

    function getValue2() external view returns (uint256) {
        return this.publicUint256();
    }
}

